wandb_version: 1

seed:
  desc: null
  value: 0
wandb_name:
  desc: null
  value: qlearn
wandb_mode:
  desc: null
  value: online
game_name:
  desc: null
  value: MountainCar-v0
llm_type:
  desc: null
  value: gpt-3.5-turbo
eval_max_steps:
  desc: null
  value: 50
cost_budget:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.1
train_iterations:
  desc: null
  value: 10000
max_tokens:
  desc: null
  value: 500
max_prompt_size:
  desc: null
  value: 3800
exp:
  desc: null
  value: react
wandb_gen_id:
  desc: null
  value: D96B5BB9-A5AE-4724-9D1D-AF8A8FD2F410
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701669974.851039
    t:
      1:
      - 50
      - 55
      2:
      - 50
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.8.18
      5: 0.16.0
      8:
      - 5
      13: darwin-x86_64
